import { AlertTriangle, ArrowRight, CheckCircle2, ShieldAlert } from 'lucide-react';
import type { Project, ProjectRequirement, Student } from '@/types';
import { analyzeTeamRiskRadar, matchStudentToProjects } from '@/lib/teamAnalysis';
import { cn } from '@/utils/cn';

const riskColor = (score: number) => score >= 75 ? 'text-brand-600' : score >= 50 ? 'text-accent-600' : 'text-rose-600';

export function OpportunityMatches({ student, projects, onRequest }: { student: Student; projects: { project: Project; requirements: ProjectRequirement[] }[]; onRequest?: (projectId: string) => void }) {
  const matches = matchStudentToProjects(student, projects);
  return <section className="card p-6"><div className="flex items-start justify-between gap-3"><div><h2 className="font-display text-xl font-700 text-ink-900">Project opportunities</h2><p className="mt-1 text-sm text-ink-500">Ranked from your stored skills, interests, availability, experience, role preferences, and commitment data.</p></div><ArrowRight className="h-5 w-5 text-brand-600" /></div><div className="mt-5 space-y-3">{matches.length ? matches.slice(0, 6).map((match) => <div key={match.project.id} className="rounded-xl border border-ink-100 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-700 text-ink-900">{match.project.title}</h3><p className="mt-1 text-xs text-ink-500">Potential role: <b className="text-ink-800">{match.potentialRole}</b></p></div><span className="font-display text-2xl font-800 text-brand-600">{match.score}%</span></div><div className="mt-3"><p className="text-xs font-700 uppercase tracking-wide text-ink-400">Why it matches</p>{match.why.length ? <ul className="mt-1 space-y-1 text-xs text-ink-600">{match.why.map((reason) => <li key={reason} className="flex items-center gap-1.5"><CheckCircle2 className="h-3.5 w-3.5 text-brand-500" />{reason}</li>)}</ul> : <p className="mt-1 text-xs text-ink-500">Limited matching data is available.</p>}</div>{match.missingRequirements.length > 0 && <p className="mt-3 text-xs text-accent-700"><b>Potential gap:</b> {match.missingRequirements.join(', ')}</p>}<button onClick={() => onRequest?.(match.project.id)} className="btn-primary mt-4 w-full sm:w-auto">Request team participation</button></div>) : <p className="rounded-xl bg-ink-50 p-4 text-sm text-ink-500">No project requirements are available yet.</p>}</div></section>;
}

export function TeamRiskRadar({ members, requirements, project }: { members: Student[]; requirements: ProjectRequirement[]; project?: Project }) {
  const radar = analyzeTeamRiskRadar(members, requirements, project);
  return <section className="card p-6"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><ShieldAlert className="h-5 w-5 text-brand-600" /><h2 className="font-display text-xl font-700 text-ink-900">Team risk radar</h2></div><p className="mt-1 text-sm text-ink-500">Scores are 0-100 health scores calculated from explicit team data. Lower scores indicate more risk.</p></div><span className="chip bg-ink-100 text-ink-600">{radar.criticalRisks.length} critical</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{radar.risks.map((risk) => <div key={risk.name} className="rounded-xl border border-ink-100 p-4"><div className="flex items-center justify-between gap-3"><span className="font-700 text-ink-900">{risk.name}</span><span className={cn('font-display text-xl font-800', riskColor(risk.score))}>{risk.score}/100</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-ink-100"><div className={cn('h-full rounded-full', risk.score >= 75 ? 'bg-brand-500' : risk.score >= 50 ? 'bg-accent-500' : 'bg-rose-500')} style={{ width: `${risk.score}%` }} /></div><p className="mt-2 text-xs leading-relaxed text-ink-500">{risk.reason}</p>{risk.score < 75 && <p className="mt-2 flex items-start gap-1 text-xs font-600 text-accent-700"><AlertTriangle className="mt-0.5 h-3.5 w-3.5 shrink-0" />{risk.recommendation}</p>}</div>)}</div></section>;
}
