import { AlertTriangle, CheckCircle2, HeartHandshake, ShieldAlert } from 'lucide-react';
import type { Project, ProjectRequirement, Student } from '@/types';
import { analyzeCommitment, analyzeTeamChemistry, analyzeTeamResilience, calculateSkillConfidence } from '@/lib/teamAnalysis';
import { cn } from '@/utils/cn';
import { TeamRiskRadar } from '@/components/OpportunityRiskPanels';

export function TeamResilienceChemistry({ members, requirements, project }: { members: Student[]; requirements: ProjectRequirement[]; project?: Project }) {
  const resilience = analyzeTeamResilience(members, requirements);
  const chemistry = analyzeTeamChemistry(members);
  return <div className="space-y-6">
    <TeamRiskRadar members={members} requirements={requirements} project={project} />
    <div className="card p-6">
      <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><ShieldAlert className="h-5 w-5 text-brand-600" /><h2 className="font-display text-xl font-700 text-ink-900">Team resilience</h2></div><p className="mt-2 text-sm text-ink-500">{resilience.explanation}</p></div><div className="rounded-xl bg-brand-50 px-4 py-2 text-center"><span className="block font-display text-2xl font-800 text-brand-600">{resilience.score}/100</span><span className="text-[10px] font-700 uppercase tracking-wide text-brand-700">resilience</span></div></div>
      <div className="mt-5 space-y-3">{resilience.skills.map((skill) => <div key={skill.skill} className="rounded-xl border border-ink-100 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><span className="font-700 text-ink-900">{skill.skill}</span><span className={cn('chip text-[11px]', skill.dependencyRisk === 'CRITICAL' || skill.dependencyRisk === 'HIGH' ? 'bg-rose-50 text-rose-700' : skill.dependencyRisk === 'MODERATE' ? 'bg-accent-50 text-accent-700' : 'bg-brand-50 text-brand-700')}>{skill.dependencyRisk} risk</span></div><div className="mt-2 grid gap-2 text-xs text-ink-500 sm:grid-cols-3"><span>Coverage: <b className="text-ink-800">{skill.coverageCount}</b></span><span>Primary: <b className="text-ink-800">{skill.primaryOwner ?? 'None'}</b></span><span>Backups: <b className="text-ink-800">{skill.backupCount}</b></span></div><p className="mt-2 text-xs leading-relaxed text-ink-500">{skill.explanation}</p>{(skill.dependencyRisk === 'CRITICAL' || skill.dependencyRisk === 'HIGH') && <p className="mt-2 flex items-center gap-1 text-xs font-600 text-rose-600"><AlertTriangle className="h-3.5 w-3.5" /> Single Point of Failure: find another {skill.skill}-capable member.</p>}</div>)}</div>
    </div>
    <div className="card p-6"><div className="flex items-center gap-2"><HeartHandshake className="h-5 w-5 text-brand-600" /><h2 className="font-display text-xl font-700 text-ink-900">Team chemistry</h2><span className="ml-auto font-display text-2xl font-800 text-brand-600">{chemistry.score}/100</span></div><p className="mt-2 text-sm text-ink-500">Pairwise compatibility uses only explicitly stored communication, collaboration, and leadership preferences.</p><div className="mt-4 space-y-2">{chemistry.strongestPairings.map((pair) => <div key={`${pair.first}-${pair.second}`} className="flex items-center justify-between rounded-lg bg-brand-50 p-3 text-sm"><span className="font-600 text-ink-800">{pair.first} ↔ {pair.second}</span><span className="font-700 text-brand-700">{pair.score}%</span></div>)}</div>{chemistry.frictionAreas.length > 0 && <div className="mt-4 rounded-xl bg-accent-50 p-3 text-xs text-accent-800"><b>Potential friction:</b> {chemistry.frictionAreas.join(' ')}</div>}</div>
    {project && <div className="card p-6"><h2 className="font-display text-xl font-700 text-ink-900">Commitment compatibility</h2><div className="mt-4 space-y-3">{members.map((member) => { const result = analyzeCommitment(project, member); return <div key={member.id} className="rounded-xl border border-ink-100 p-4"><div className="flex items-center justify-between"><span className="font-600 text-ink-900">{member.name}</span><span className="font-800 text-brand-600">{result.score ? `${result.score}%` : 'Not enough data'}</span></div><p className="mt-1 text-xs text-ink-500">{result.explanation}</p>{result.warnings.map((warning) => <p key={warning} className="mt-2 flex items-start gap-1 text-xs font-600 text-rose-600"><AlertTriangle className="mt-0.5 h-3.5 w-3.5 shrink-0" />{warning}</p>)}{!result.warnings.length && result.score > 0 && <p className="mt-2 flex items-center gap-1 text-xs text-brand-600"><CheckCircle2 className="h-3.5 w-3.5" /> {result.risk} risk</p>}</div>; })}</div></div>}
    <div className="card p-6"><h2 className="font-display text-xl font-700 text-ink-900">Skill confidence</h2><p className="mt-2 text-sm text-ink-500">Self-rating and evidence are shown separately. Confidence never treats a self-rating as verification.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{members.flatMap((member) => member.skills.slice(0, 3).map((skill) => { const confidence = calculateSkillConfidence(skill); return <div key={`${member.id}-${skill.skillId}`} className="rounded-xl border border-ink-100 p-3"><div className="flex items-center justify-between"><span className="text-sm font-700 text-ink-900">{member.name}: {confidence.skill}</span><span className="text-sm font-800 text-brand-600">{confidence.confidence}%</span></div><p className="mt-1 text-xs text-ink-500">Self Rating: {confidence.selfRating}/5 · Evidence: {confidence.evidenceCount} item{confidence.evidenceCount === 1 ? '' : 's'}</p><p className="mt-1 text-xs text-ink-400">{confidence.explanation}</p></div>; }))}</div></div>
  </div>;
}